site_name: MultiRoute Tour!
site_url: https://tour.multiroute.de/handbuch/

nav:
    - Home: index.md
    - Handbuch:
      - Übersicht: uebersicht.md
      - Einführung: einfuehrung.md
      - 1. Upload: upload.md
      - 2. Planung: planung.md
      - 3. Flotten: flotten.md
      - 4. Touren: tour.md
      - Tipps & Tricks: tipps.md
      - Wochenplanung: wochenplanung.md
      - Changelog: changelog.md
    - Anwendungsbeispiele:
      - Spedition: spediteur.md
      - Außendienst: aussendienst.md
      - Schneeräumung: schneeraeumung.md
      - Essen auf Rädern: essen_auf_raedern.md
      - Getränkelieferungen: getraenkelieferung.md
      - Lieferkisten: lieferkiste.md
      - Gebäudereinigung: gebaeudereinigung.md
    - API:
      - MRT! API: api-intro.md
      - Einführung: ablauf.md
      - Routen & Endpunkte: routen.md
      - Beispiele:
        - Python: mrt-api-python.md
        - PHP: mrt-api-php.md
#    - Referenzen: 14.md
    - Preise: preise.md
    - Impressum: impressum.md
    - Datenschutz: datenschutz.md

theme:
  name: material
  custom_dir: docs/theme_override_home/
  # 404 page
  static_templates:
    - 404.html
  # enable light/dark mode
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true
  # Default values, taken from mkdocs_theme.yml
  language: de
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.footer
    - content.action.edit
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    
  font: false
  icon:  # from .icons path. Add to theme override for custom logo.
    logo: truck  # top left header logo
    repo: fontawesome/brands/git-alt
    edit: material/file-edit-outline
  favicon: assets/favicon.ico #browser tab logo

extra_javascript:
        - stylesheets/extra.js
        - stylesheets/tablesort.min.js
        - stylesheets/tablesort.js
extra_css:
        - stylesheets/extra.css
        - stylesheets/font-awesome-4.7.0/css/font-awesome.min.css

repo_url: https://github.com/gbconsite/MultiRoute-Tour
repo_name: gbconsite/MultiRoute-Tour
edit_uri: ./edit/main/docs

markdown_extensions:
  - attr_list
  - md_in_html # enable lazy loading images via ![!](assets/Auftragsinfos.jpg){ loading=lazy }
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.toc:
      baselevel: 1
      permalink: true
  - toc:
      title: Inhalt
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
  - search:
      lang: de
  - glightbox

#extra:
#  alternate:
#    - name: Deutsch
#      link: 
#      lang: de
#    - name: English
#      link: /en/ 
#      lang: en
