name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Set up Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # Install uv and dependencies with uv instead of pip
      - run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip install "mkdocs-material[imaging]==9.5.18"
          uv pip install mkdocs-glightbox mkdocs-minify-plugin
          
      # Deploy with mkdocs
      - run: mkdocs gh-deploy --force

      # Node setup
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install gzipper with npm
      - run: npm install
      - run: npm install -g gzipper@7.2.0

      # Check out other branch (gh-pages)
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      # Compress all files in all directories
      - run: gzipper compress --include htm,html,css,js,svg,xml,map,json,img,png,jpg,jpeg --zopfli --brotli --remove-larger .

      # Commit compressed files
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Compress Files
          branch: gh-pages
          push_options: '--force'
